# Generated by Django 4.2.1 on 2023-05-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='hotel_address',
            field=models.CharField(default='Lima', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='hotel_name',
            field=models.CharField(default='Hotel 5 stars', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='hotel_ruc',
            field=models.CharField(default='12345678910', max_length=11),
        ),
    ]
