# Generated by Django 4.2.1 on 2023-05-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_rename_fecha_fin_reservation_date_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.FloatField(),
        ),
    ]
